name: Regénération Environnementale Tempête et Espace

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connexion au dépôt
        uses: actions/checkout@v4

      - name: Lancement de Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Fusion NASA et Satellites Météo
        run: python calculer_orbites.py

      - name: Configuration de Pages
        uses: actions/configure-pages@v4

      - name: Téléchargement de l'artefact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Déploiement public
        uses: actions/deploy-pages@v4
