name: SENTINELA - Horloge Atomique Calendaire

on:
  schedule:
    - cron: '0 0 * * *' # S'exécute tous les jours à minuit
  workflow_dispatch: # Permet le déclenchement manuel

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Récupération du dépôt
      uses: actions/checkout@v3

    - name: Configuration de Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Installation des dépendances
      run: pip install requests

    - name: Extraction des données brutes JPL-NASA
      run: python calculer_orbites.py  # <-- C'EST CETTE LIGNE QUI DOIT TOURNER

    - name: Commit et Push des nouvelles orbites
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add orbites.json
        git commit -m "Update orbites.json [JPL-NASA v8.9.1]" || exit 0
        git push
