name: SENTINELA - Horloge Atomique Calendaire

on:
  schedule:
    - cron: '5 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Récupération du code source
      uses: actions/checkout@v4
      with:
        persist-credentials: true

    - name: Configuration de l'environnement Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Installation des dépendances réseau
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Exécution du calcul orbital NASA
      run: python calculer_orbites.py

    - name: Sauvegarde et Push de la matrice orbites.json
      env:
        HF_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "nicolaspieper59-ops"
        git config --global user.email "nicolaspieper59-ops@users.noreply.github.com"
        git add orbites.json
        
        # Vérification s'il y a des changements à pousser
        if ! git diff --cached --quiet; then
          git commit -m "Mise à jour cinématique automatique [NASA UTC]"
          # Forçage de l'authentification avec le jeton d'action pour le push
          git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
          git push origin main
        else
          echo "Aucune modification détectée sur la matrice éphémérides."
        fi
